### ISSUE TITLE
cannot train with ml engine/install it 

### ISSUE THREAD

**Issue by brandondutra** [TensorLab/tensorfx#11]
Found this while trying cloud training. Error can be done locally with:

$ pwd
.../tensorfx/build/dist
$ pip install --upgrade --force-reinstall tensorfx-0.1.4.tar.gz 
Processing ./tensorfx-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-qs8P7n-build/setup.py", line 22, in <module>
        with open('requirements.txt') as rf:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-qs8P7n-build/

**Comment by brandondutra** [comment]
problem: setuptools >= 34.3.1 is needed. I built the tar ball with 28.2.0 the first time and got this error.

**Comment by brandondutra** [comment]
sent PR #12  to check for this in build.sh. min setuptools needed is 30

**Comment by brandondutra** [comment]
min setuptools needed is 30

**Comment by nikhilk** [comment]
Is this a pecularity of the internal goobuntu setup? I certainly didn't hit it on my mac where I use miniconda (but not a virtual or conda env).

**Comment by brandondutra** [comment]
which version of setuptools did you use?

**Comment by nikhilk** [comment]
I used whatever comes by standard with miniconda (as far as I remember, I didn't install it explicitly) which happens to be 34.2.0.

I checked on ubuntu. It is 26.1.1, and so this must be an ubuntu thing.

Does it make sense to require using miniconda as a starting point for the development enviornment, so there is a possibility of consistent environment?
