### ISSUE TITLE
has this been tested on a mac?

### ISSUE THREAD

**Issue by brandondutra** [TensorLab/tensorfx#4]
I downloaded a clean repro, ran source init.sh and build.sh. The model somehow is not written to /tmp.

If I set --output to a different folder, I get the same error.

(cml-virtualenv) brandondutra-macbookpro:bdtensorfx brandondutra$ source init.sh 
(cml-virtualenv) brandondutra-macbookpro:bdtensorfx brandondutra$ ./build.sh 
Build completed successfully!
Samples copied successfully!
Tests copied successfully!
(cml-virtualenv) brandondutra-macbookpro:bdtensorfx brandondutra$ ./samples/census/run.sh 
Launching training task...
python -m census.train --data-train samples/census/data/train.csv --data-eval samples/census/data/eval.csv --data-schema samples/census/data/schema.yaml --data-metadata samples/census/data/metadata.json --data-features samples/census/features.yaml --log-level-tensorflow ERROR --log-level INFO --batch-size 5 --max-steps 1000 --checkpoint-interval-secs 1 --hidden-layers:1 200 --hidden-layers:2 100 --hidden-layers:3 20 --job_dir /tmp/tensorfx/census

INFO: Run: 0.04 sec; Steps: 1; Duration: 0 sec; Throughput: 6.4 instances/sec
INFO: Global steps: 1002; Evaluation metric: 0.824
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/brandondutra/Documents/bdtensorfx/samples/census/train.py", line 29, in <module>
    trainer.train(classification, job)
  File "tensorfx/training/_trainer.py", line 60, in train
    return self._run_training(server, job)
  File "tensorfx/training/_trainer.py", line 99, in _run_training
    return tfx.prediction.Model.load(job.model_path)
  File "tensorfx/prediction/_model.py", line 51, in load
    metagraph = tf.saved_model.loader.load(session, ['SERVING'], path)
  File "/Users/brandondutra/cml-virtualenv/lib/python2.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 199, in load
    saved_model = _parse_saved_model(export_dir)
  File "/Users/brandondutra/cml-virtualenv/lib/python2.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 60, in _parse_saved_model
    raise IOError("SavedModel file does not exist at: %s" % export_dir)
IOError: SavedModel file does not exist at: /tmp/tensorfx/census/model
(cml-virtualenv) brandondutra-macbookpro:bdtensorfx brandondutra$ ls /tmp/tensorfx/census/
checkpoints	job.yaml	summaries

**Comment by brandondutra** [comment]
with your newest set of changes, running on a mac works :)
